/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_HELLOWORLD_U_H
#define EDGER8R_HELLOWORLD_U_H

#include <openenclave/host.h>
#include "helloworld_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_helloworld_enclave(const char* path,
                                 oe_enclave_type_t type,
                                 uint32_t flags,
                                 const void* config,
                                 uint32_t config_size,
                                 oe_enclave_t** enclave);

/* List of ecalls */

oe_result_t ecall_run(
        oe_enclave_t* enclave,
        int* _retval,
        const char* input,
        uint64_t input_len,
        char** output,
        uint64_t max_len,
        uint64_t* output_len);
oe_result_t ecall_InitializeSockets(
        oe_enclave_t* enclave);
oe_result_t enc_enclave_thread(
        oe_enclave_t* enclave,
        uint64_t enc_key);

/* List of ocalls */

accept_Result ocall_accept(intptr_t a_hSocket,
        int a_nAddrLen);
oe_socket_error_t ocall_bind(intptr_t a_hSocket,
        const void* a_Name,
        int a_nNameLen);
oe_socket_error_t ocall_closesocket(intptr_t a_hSocket);
oe_socket_error_t ocall_connect(intptr_t a_hSocket,
        const void* a_Name,
        int a_nNameLen);
int ocall_getaddrinfo(const char* a_NodeName,
        const char* a_ServiceName,
        int a_Flags,
        int a_Family,
        int a_SockType,
        int a_Protocol,
        addrinfo_Buffer* buf,
        size_t len,
        size_t* length_needed);
gethostname_Result ocall_gethostname(void);
getnameinfo_Result ocall_getnameinfo(const void* a_Addr,
        int a_AddrLen,
        int a_Flags);
GetSockName_Result ocall_getpeername(intptr_t a_hSocket,
        int a_nNameLen);
GetSockName_Result ocall_getsockname(intptr_t a_hSocket,
        int a_nNameLen);
getsockopt_Result ocall_getsockopt(intptr_t a_hSocket,
        int a_nLevel,
        int a_nOptName,
        int a_nOptLen);
ioctlsocket_Result ocall_ioctlsocket(intptr_t a_hSocket,
        int a_nCommand,
        unsigned int a_uInputValue);
oe_socket_error_t ocall_listen(intptr_t a_hSocket,
        int a_nMaxConnections);
ssize_t ocall_recv(intptr_t s,
        void* buf,
        size_t len,
        int flags,
        oe_socket_error_t* error);
select_Result ocall_select(int a_nFds,
        oe_fd_set_internal a_ReadFds,
        oe_fd_set_internal a_WriteFds,
        oe_fd_set_internal a_ExceptFds,
        struct timeval a_Timeval);
send_Result ocall_send(intptr_t a_hSocket,
        const void* a_Message,
        size_t a_nMessageLen,
        int a_Flags);
oe_socket_error_t ocall_setsockopt(intptr_t a_hSocket,
        int a_nLevel,
        int a_nOptName,
        const void* a_OptVal,
        int a_nOptLen);
oe_socket_error_t ocall_shutdown(intptr_t a_hSocket,
        oe_shutdown_how_t a_How);
socket_Result ocall_socket(oe_socket_address_family_t a_AddressFamily,
        oe_socket_type_t a_Type,
        int a_Protocol);
oe_socket_error_t ocall_WSACleanup(void);
oe_socket_error_t ocall_WSAStartup(void);
void host_exit(int arg);
void host_create_thread(uint64_t enc_key,
        oe_enclave_t* enc);
int host_join_thread(uint64_t enc_key);
int host_detach_thread(uint64_t enc_key);
oe_pthread_condattr_init_result_t oe_host_ocall_pthread_condattr_init(pthread_condattr_t* a);
oe_pthread_condattr_destroy_result_t oe_host_ocall_pthread_condattr_destroy(pthread_condattr_t* a);
oe_pthread_condattr_getpshared_result_t oe_host_ocall_pthread_condattr_getpshared(const pthread_condattr_t* a,
        int* b);
oe_pthread_condattr_setpshared_result_t oe_host_ocall_pthread_condattr_setpshared(pthread_condattr_t* a,
        int b);
oe_pthread_condattr_getclock_result_t oe_host_ocall_pthread_condattr_getclock(const pthread_condattr_t* a,
        clockid_t* b);
oe_pthread_condattr_setclock_result_t oe_host_ocall_pthread_condattr_setclock(pthread_condattr_t* a,
        clockid_t b);
oe_pthread_attr_init_result_t oe_host_ocall_pthread_attr_init(pthread_attr_t* a);
oe_pthread_attr_destroy_result_t oe_host_ocall_pthread_attr_destroy(pthread_attr_t* a);
oe_pthread_attr_setdetachstate_result_t oe_host_ocall_pthread_attr_setdetachstate(pthread_attr_t* a,
        int b);
oe_eventfd_result_t oe_host_ocall_eventfd(unsigned int a,
        int b);
oe_eventfd_read_result_t oe_host_ocall_eventfd_read(int a,
        eventfd_t* b);
oe_eventfd_write_result_t oe_host_ocall_eventfd_write(int a,
        eventfd_t b);

OE_EXTERNC_END

#endif // EDGER8R_HELLOWORLD_U_H
