/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef HELLOWORLD_ARGS_H
#define HELLOWORLD_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */ 

#include <openenclave/bits/result.h>

#include "openenclave/bits/sockettypes.h"
#include "openenclave/bits/timetypes.h"
#include "pthread.h"
#include "pthread_types.h"
#include "sys/eventfd.h"
#include "eventfd_types.h"

/* User types specified in edl */
typedef struct accept_Result {
    oe_socket_error_t error;
    intptr_t hNewSocket;
    int addrlen;
    char addr[256];
} accept_Result;

typedef struct addrinfo_Buffer {
    int ai_flags;
    int ai_family;
    int ai_socktype;
    int ai_protocol;
    int ai_addrlen;
    char ai_canonname[256];
    char ai_addr[256];
} addrinfo_Buffer;

typedef struct gethostname_Result {
    oe_socket_error_t error;
    char name[256];
} gethostname_Result;

typedef struct getnameinfo_Result {
    oe_socket_error_t error;
    char host[256];
    char serv[256];
} getnameinfo_Result;

typedef struct GetSockName_Result {
    oe_socket_error_t error;
    int addrlen;
    char addr[256];
} GetSockName_Result;

typedef struct getsockopt_Result {
    oe_socket_error_t error;
    char buffer[256];
    int len;
} getsockopt_Result;

typedef struct ioctlsocket_Result {
    oe_socket_error_t error;
    unsigned int outputValue;
} ioctlsocket_Result;

typedef struct oe_fd_set_internal {
    unsigned int fd_count;
    intptr_t fd_array[64];
} oe_fd_set_internal;

typedef struct select_Result {
    oe_socket_error_t error;
    int socketsSet;
    oe_fd_set_internal readFds;
    oe_fd_set_internal writeFds;
    oe_fd_set_internal exceptFds;
} select_Result;

typedef struct send_Result {
    oe_socket_error_t error;
    int bytesSent;
} send_Result;

typedef struct socket_Result {
    oe_socket_error_t error;
    intptr_t hSocket;
} socket_Result;

typedef enum string_limit {
    STRLEN = 1024} string_limit;


typedef struct _ecall_run_args_t {
	int _retval;
	char* input;
	uint64_t input_len;
	char** output;
	uint64_t max_len;
	uint64_t* output_len;
    oe_result_t _result;
 } ecall_run_args_t;

typedef struct _ecall_InitializeSockets_args_t {
    oe_result_t _result;
 } ecall_InitializeSockets_args_t;

typedef struct _enc_enclave_thread_args_t {
	uint64_t enc_key;
    oe_result_t _result;
 } enc_enclave_thread_args_t;

typedef struct _ocall_accept_args_t {
	accept_Result _retval;
	intptr_t a_hSocket;
	int a_nAddrLen;
    oe_result_t _result;
 } ocall_accept_args_t;

typedef struct _ocall_bind_args_t {
	oe_socket_error_t _retval;
	intptr_t a_hSocket;
	void* a_Name;
	int a_nNameLen;
    oe_result_t _result;
 } ocall_bind_args_t;

typedef struct _ocall_closesocket_args_t {
	oe_socket_error_t _retval;
	intptr_t a_hSocket;
    oe_result_t _result;
 } ocall_closesocket_args_t;

typedef struct _ocall_connect_args_t {
	oe_socket_error_t _retval;
	intptr_t a_hSocket;
	void* a_Name;
	int a_nNameLen;
    oe_result_t _result;
 } ocall_connect_args_t;

typedef struct _ocall_getaddrinfo_args_t {
	int _retval;
	char* a_NodeName;
	size_t a_NodeName_len;
	char* a_ServiceName;
	size_t a_ServiceName_len;
	int a_Flags;
	int a_Family;
	int a_SockType;
	int a_Protocol;
	addrinfo_Buffer* buf;
	size_t len;
	size_t* length_needed;
    oe_result_t _result;
 } ocall_getaddrinfo_args_t;

typedef struct _ocall_gethostname_args_t {
	gethostname_Result _retval;
    oe_result_t _result;
 } ocall_gethostname_args_t;

typedef struct _ocall_getnameinfo_args_t {
	getnameinfo_Result _retval;
	void* a_Addr;
	int a_AddrLen;
	int a_Flags;
    oe_result_t _result;
 } ocall_getnameinfo_args_t;

typedef struct _ocall_getpeername_args_t {
	GetSockName_Result _retval;
	intptr_t a_hSocket;
	int a_nNameLen;
    oe_result_t _result;
 } ocall_getpeername_args_t;

typedef struct _ocall_getsockname_args_t {
	GetSockName_Result _retval;
	intptr_t a_hSocket;
	int a_nNameLen;
    oe_result_t _result;
 } ocall_getsockname_args_t;

typedef struct _ocall_getsockopt_args_t {
	getsockopt_Result _retval;
	intptr_t a_hSocket;
	int a_nLevel;
	int a_nOptName;
	int a_nOptLen;
    oe_result_t _result;
 } ocall_getsockopt_args_t;

typedef struct _ocall_ioctlsocket_args_t {
	ioctlsocket_Result _retval;
	intptr_t a_hSocket;
	int a_nCommand;
	unsigned int a_uInputValue;
    oe_result_t _result;
 } ocall_ioctlsocket_args_t;

typedef struct _ocall_listen_args_t {
	oe_socket_error_t _retval;
	intptr_t a_hSocket;
	int a_nMaxConnections;
    oe_result_t _result;
 } ocall_listen_args_t;

typedef struct _ocall_recv_args_t {
	ssize_t _retval;
	intptr_t s;
	void* buf;
	size_t len;
	int flags;
	oe_socket_error_t* error;
    oe_result_t _result;
 } ocall_recv_args_t;

typedef struct _ocall_select_args_t {
	select_Result _retval;
	int a_nFds;
	oe_fd_set_internal a_ReadFds;
	oe_fd_set_internal a_WriteFds;
	oe_fd_set_internal a_ExceptFds;
	struct timeval a_Timeval;
    oe_result_t _result;
 } ocall_select_args_t;

typedef struct _ocall_send_args_t {
	send_Result _retval;
	intptr_t a_hSocket;
	void* a_Message;
	size_t a_nMessageLen;
	int a_Flags;
    oe_result_t _result;
 } ocall_send_args_t;

typedef struct _ocall_setsockopt_args_t {
	oe_socket_error_t _retval;
	intptr_t a_hSocket;
	int a_nLevel;
	int a_nOptName;
	void* a_OptVal;
	int a_nOptLen;
    oe_result_t _result;
 } ocall_setsockopt_args_t;

typedef struct _ocall_shutdown_args_t {
	oe_socket_error_t _retval;
	intptr_t a_hSocket;
	oe_shutdown_how_t a_How;
    oe_result_t _result;
 } ocall_shutdown_args_t;

typedef struct _ocall_socket_args_t {
	socket_Result _retval;
	oe_socket_address_family_t a_AddressFamily;
	oe_socket_type_t a_Type;
	int a_Protocol;
    oe_result_t _result;
 } ocall_socket_args_t;

typedef struct _ocall_WSACleanup_args_t {
	oe_socket_error_t _retval;
    oe_result_t _result;
 } ocall_WSACleanup_args_t;

typedef struct _ocall_WSAStartup_args_t {
	oe_socket_error_t _retval;
    oe_result_t _result;
 } ocall_WSAStartup_args_t;

typedef struct _host_exit_args_t {
	int arg;
    oe_result_t _result;
 } host_exit_args_t;

typedef struct _host_create_thread_args_t {
	uint64_t enc_key;
	oe_enclave_t* enc;
    oe_result_t _result;
 } host_create_thread_args_t;

typedef struct _host_join_thread_args_t {
	int _retval;
	uint64_t enc_key;
    oe_result_t _result;
 } host_join_thread_args_t;

typedef struct _host_detach_thread_args_t {
	int _retval;
	uint64_t enc_key;
    oe_result_t _result;
 } host_detach_thread_args_t;

typedef struct _oe_host_ocall_pthread_condattr_init_args_t {
	oe_pthread_condattr_init_result_t _retval;
	pthread_condattr_t* a;
    oe_result_t _result;
 } oe_host_ocall_pthread_condattr_init_args_t;

typedef struct _oe_host_ocall_pthread_condattr_destroy_args_t {
	oe_pthread_condattr_destroy_result_t _retval;
	pthread_condattr_t* a;
    oe_result_t _result;
 } oe_host_ocall_pthread_condattr_destroy_args_t;

typedef struct _oe_host_ocall_pthread_condattr_getpshared_args_t {
	oe_pthread_condattr_getpshared_result_t _retval;
	pthread_condattr_t* a;
	int* b;
    oe_result_t _result;
 } oe_host_ocall_pthread_condattr_getpshared_args_t;

typedef struct _oe_host_ocall_pthread_condattr_setpshared_args_t {
	oe_pthread_condattr_setpshared_result_t _retval;
	pthread_condattr_t* a;
	int b;
    oe_result_t _result;
 } oe_host_ocall_pthread_condattr_setpshared_args_t;

typedef struct _oe_host_ocall_pthread_condattr_getclock_args_t {
	oe_pthread_condattr_getclock_result_t _retval;
	pthread_condattr_t* a;
	clockid_t* b;
    oe_result_t _result;
 } oe_host_ocall_pthread_condattr_getclock_args_t;

typedef struct _oe_host_ocall_pthread_condattr_setclock_args_t {
	oe_pthread_condattr_setclock_result_t _retval;
	pthread_condattr_t* a;
	clockid_t b;
    oe_result_t _result;
 } oe_host_ocall_pthread_condattr_setclock_args_t;

typedef struct _oe_host_ocall_pthread_attr_init_args_t {
	oe_pthread_attr_init_result_t _retval;
	pthread_attr_t* a;
    oe_result_t _result;
 } oe_host_ocall_pthread_attr_init_args_t;

typedef struct _oe_host_ocall_pthread_attr_destroy_args_t {
	oe_pthread_attr_destroy_result_t _retval;
	pthread_attr_t* a;
    oe_result_t _result;
 } oe_host_ocall_pthread_attr_destroy_args_t;

typedef struct _oe_host_ocall_pthread_attr_setdetachstate_args_t {
	oe_pthread_attr_setdetachstate_result_t _retval;
	pthread_attr_t* a;
	int b;
    oe_result_t _result;
 } oe_host_ocall_pthread_attr_setdetachstate_args_t;

typedef struct _oe_host_ocall_eventfd_args_t {
	oe_eventfd_result_t _retval;
	unsigned int a;
	int b;
    oe_result_t _result;
 } oe_host_ocall_eventfd_args_t;

typedef struct _oe_host_ocall_eventfd_read_args_t {
	oe_eventfd_read_result_t _retval;
	int a;
	eventfd_t* b;
    oe_result_t _result;
 } oe_host_ocall_eventfd_read_args_t;

typedef struct _oe_host_ocall_eventfd_write_args_t {
	oe_eventfd_write_result_t _retval;
	int a;
	eventfd_t b;
    oe_result_t _result;
 } oe_host_ocall_eventfd_write_args_t;

/* trusted function ids */
enum {
    fcn_id_ecall_run = 0,
    fcn_id_ecall_InitializeSockets = 1,
    fcn_id_enc_enclave_thread = 2,
    fcn_id_trusted_call_id_max = OE_ENUM_MAX
};


/* untrusted function ids */
enum {
    fcn_id_ocall_accept = 0,
    fcn_id_ocall_bind = 1,
    fcn_id_ocall_closesocket = 2,
    fcn_id_ocall_connect = 3,
    fcn_id_ocall_getaddrinfo = 4,
    fcn_id_ocall_gethostname = 5,
    fcn_id_ocall_getnameinfo = 6,
    fcn_id_ocall_getpeername = 7,
    fcn_id_ocall_getsockname = 8,
    fcn_id_ocall_getsockopt = 9,
    fcn_id_ocall_ioctlsocket = 10,
    fcn_id_ocall_listen = 11,
    fcn_id_ocall_recv = 12,
    fcn_id_ocall_select = 13,
    fcn_id_ocall_send = 14,
    fcn_id_ocall_setsockopt = 15,
    fcn_id_ocall_shutdown = 16,
    fcn_id_ocall_socket = 17,
    fcn_id_ocall_WSACleanup = 18,
    fcn_id_ocall_WSAStartup = 19,
    fcn_id_host_exit = 20,
    fcn_id_host_create_thread = 21,
    fcn_id_host_join_thread = 22,
    fcn_id_host_detach_thread = 23,
    fcn_id_oe_host_ocall_pthread_condattr_init = 24,
    fcn_id_oe_host_ocall_pthread_condattr_destroy = 25,
    fcn_id_oe_host_ocall_pthread_condattr_getpshared = 26,
    fcn_id_oe_host_ocall_pthread_condattr_setpshared = 27,
    fcn_id_oe_host_ocall_pthread_condattr_getclock = 28,
    fcn_id_oe_host_ocall_pthread_condattr_setclock = 29,
    fcn_id_oe_host_ocall_pthread_attr_init = 30,
    fcn_id_oe_host_ocall_pthread_attr_destroy = 31,
    fcn_id_oe_host_ocall_pthread_attr_setdetachstate = 32,
    fcn_id_oe_host_ocall_eventfd = 33,
    fcn_id_oe_host_ocall_eventfd_read = 34,
    fcn_id_oe_host_ocall_eventfd_write = 35,
    fcn_id_untrusted_call_max = OE_ENUM_MAX
};


#endif // HELLOWORLD_ARGS_H
