/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "helloworld_u.h"
#include <openenclave/edger8r/host.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>

OE_EXTERNC_BEGIN

/* Wrappers for ecalls */

oe_result_t ecall_run(
        oe_enclave_t* enclave,
        int* _retval,
        const char* input,
        uint64_t input_len,
        char** output,
        uint64_t max_len,
        uint64_t* output_len)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshaling struct */ 
    ecall_run_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshaling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshaling struct */
    memset(&_args, 0, sizeof(_args));
    _args.input = (char*) input;
    _args.input_len = input_len;
    _args.output = (char**) output;
    _args.max_len = max_len;
    _args.output_len = (uint64_t*) output_len;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_run_args_t));
    if (input) OE_ADD_SIZE(_input_buffer_size, _args.input_len);

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_run_args_t));
    if (output) OE_ADD_SIZE(_output_buffer_size, _args.max_len);
    if (output_len) OE_ADD_SIZE(_output_buffer_size, sizeof(uint64_t));

    /* Allocate marshaling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));

    OE_WRITE_IN_PARAM(input, _args.input_len);

    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function */
    if((_result = oe_call_enclave_function(
                        enclave,
                        fcn_id_ecall_run,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer*/
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */
    *_retval = _pargs_out->_retval;
    OE_READ_OUT_PARAM(output, (size_t)(_args.max_len));
    OE_READ_OUT_PARAM(output_len, (size_t)(sizeof(uint64_t)));

    _result = OE_OK;
done:    
    if (_buffer)
        free(_buffer);
    return _result;
}



oe_result_t ecall_InitializeSockets(
        oe_enclave_t* enclave)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshaling struct */ 
    ecall_InitializeSockets_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshaling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshaling struct */
    memset(&_args, 0, sizeof(_args));

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_InitializeSockets_args_t));

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_InitializeSockets_args_t));

    /* Allocate marshaling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));


    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function */
    if((_result = oe_call_enclave_function(
                        enclave,
                        fcn_id_ecall_InitializeSockets,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer*/
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */

    _result = OE_OK;
done:    
    if (_buffer)
        free(_buffer);
    return _result;
}



oe_result_t enc_enclave_thread(
        oe_enclave_t* enclave,
        uint64_t enc_key)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshaling struct */ 
    enc_enclave_thread_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshaling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshaling struct */
    memset(&_args, 0, sizeof(_args));
    _args.enc_key = enc_key;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(enc_enclave_thread_args_t));

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(enc_enclave_thread_args_t));

    /* Allocate marshaling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));


    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function */
    if((_result = oe_call_enclave_function(
                        enclave,
                        fcn_id_enc_enclave_thread,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer*/
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */

    _result = OE_OK;
done:    
    if (_buffer)
        free(_buffer);
    return _result;
}




/* ocall functions */

void ocall_ocall_accept(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_accept_args_t* pargs_in = (ocall_accept_args_t*) input_buffer;
    ocall_accept_args_t* pargs_out = (ocall_accept_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_accept(
        pargs_in->a_hSocket,
        pargs_in->a_nAddrLen);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_bind(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_bind_args_t* pargs_in = (ocall_bind_args_t*) input_buffer;
    ocall_bind_args_t* pargs_out = (ocall_bind_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(a_Name, pargs_in->a_nNameLen);

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_bind(
        pargs_in->a_hSocket,
        (const void*) pargs_in->a_Name,
        pargs_in->a_nNameLen);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_closesocket(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_closesocket_args_t* pargs_in = (ocall_closesocket_args_t*) input_buffer;
    ocall_closesocket_args_t* pargs_out = (ocall_closesocket_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_closesocket(
        pargs_in->a_hSocket);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_connect(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_connect_args_t* pargs_in = (ocall_connect_args_t*) input_buffer;
    ocall_connect_args_t* pargs_out = (ocall_connect_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(a_Name, pargs_in->a_nNameLen);

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_connect(
        pargs_in->a_hSocket,
        (const void*) pargs_in->a_Name,
        pargs_in->a_nNameLen);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_getaddrinfo(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_getaddrinfo_args_t* pargs_in = (ocall_getaddrinfo_args_t*) input_buffer;
    ocall_getaddrinfo_args_t* pargs_out = (ocall_getaddrinfo_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(a_NodeName, pargs_in->a_NodeName_len * sizeof(char));
    OE_SET_IN_POINTER(a_ServiceName, pargs_in->a_ServiceName_len * sizeof(char));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_SET_OUT_POINTER(buf, pargs_in->len);
    OE_SET_OUT_POINTER(length_needed, sizeof(size_t));

    /* Call user function */
    pargs_out->_retval = ocall_getaddrinfo(
        (const char*) pargs_in->a_NodeName,
        (const char*) pargs_in->a_ServiceName,
        pargs_in->a_Flags,
        pargs_in->a_Family,
        pargs_in->a_SockType,
        pargs_in->a_Protocol,
        pargs_in->buf,
        pargs_in->len,
        pargs_in->length_needed);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_gethostname(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_gethostname_args_t* pargs_in = (ocall_gethostname_args_t*) input_buffer;
    ocall_gethostname_args_t* pargs_out = (ocall_gethostname_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_gethostname(
        );

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_getnameinfo(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_getnameinfo_args_t* pargs_in = (ocall_getnameinfo_args_t*) input_buffer;
    ocall_getnameinfo_args_t* pargs_out = (ocall_getnameinfo_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(a_Addr, pargs_in->a_AddrLen);

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_getnameinfo(
        (const void*) pargs_in->a_Addr,
        pargs_in->a_AddrLen,
        pargs_in->a_Flags);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_getpeername(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_getpeername_args_t* pargs_in = (ocall_getpeername_args_t*) input_buffer;
    ocall_getpeername_args_t* pargs_out = (ocall_getpeername_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_getpeername(
        pargs_in->a_hSocket,
        pargs_in->a_nNameLen);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_getsockname(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_getsockname_args_t* pargs_in = (ocall_getsockname_args_t*) input_buffer;
    ocall_getsockname_args_t* pargs_out = (ocall_getsockname_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_getsockname(
        pargs_in->a_hSocket,
        pargs_in->a_nNameLen);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_getsockopt(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_getsockopt_args_t* pargs_in = (ocall_getsockopt_args_t*) input_buffer;
    ocall_getsockopt_args_t* pargs_out = (ocall_getsockopt_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_getsockopt(
        pargs_in->a_hSocket,
        pargs_in->a_nLevel,
        pargs_in->a_nOptName,
        pargs_in->a_nOptLen);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_ioctlsocket(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_ioctlsocket_args_t* pargs_in = (ocall_ioctlsocket_args_t*) input_buffer;
    ocall_ioctlsocket_args_t* pargs_out = (ocall_ioctlsocket_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_ioctlsocket(
        pargs_in->a_hSocket,
        pargs_in->a_nCommand,
        pargs_in->a_uInputValue);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_listen(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_listen_args_t* pargs_in = (ocall_listen_args_t*) input_buffer;
    ocall_listen_args_t* pargs_out = (ocall_listen_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_listen(
        pargs_in->a_hSocket,
        pargs_in->a_nMaxConnections);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_recv(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_recv_args_t* pargs_in = (ocall_recv_args_t*) input_buffer;
    ocall_recv_args_t* pargs_out = (ocall_recv_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_SET_OUT_POINTER(buf, pargs_in->len);
    OE_SET_OUT_POINTER(error, sizeof(oe_socket_error_t));

    /* Call user function */
    pargs_out->_retval = ocall_recv(
        pargs_in->s,
        pargs_in->buf,
        pargs_in->len,
        pargs_in->flags,
        pargs_in->error);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_select(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_select_args_t* pargs_in = (ocall_select_args_t*) input_buffer;
    ocall_select_args_t* pargs_out = (ocall_select_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_select(
        pargs_in->a_nFds,
        pargs_in->a_ReadFds,
        pargs_in->a_WriteFds,
        pargs_in->a_ExceptFds,
        pargs_in->a_Timeval);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_send(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_send_args_t* pargs_in = (ocall_send_args_t*) input_buffer;
    ocall_send_args_t* pargs_out = (ocall_send_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(a_Message, pargs_in->a_nMessageLen);

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_send(
        pargs_in->a_hSocket,
        (const void*) pargs_in->a_Message,
        pargs_in->a_nMessageLen,
        pargs_in->a_Flags);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_setsockopt(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_setsockopt_args_t* pargs_in = (ocall_setsockopt_args_t*) input_buffer;
    ocall_setsockopt_args_t* pargs_out = (ocall_setsockopt_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(a_OptVal, pargs_in->a_nOptLen);

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_setsockopt(
        pargs_in->a_hSocket,
        pargs_in->a_nLevel,
        pargs_in->a_nOptName,
        (const void*) pargs_in->a_OptVal,
        pargs_in->a_nOptLen);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_shutdown(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_shutdown_args_t* pargs_in = (ocall_shutdown_args_t*) input_buffer;
    ocall_shutdown_args_t* pargs_out = (ocall_shutdown_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_shutdown(
        pargs_in->a_hSocket,
        pargs_in->a_How);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_socket(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_socket_args_t* pargs_in = (ocall_socket_args_t*) input_buffer;
    ocall_socket_args_t* pargs_out = (ocall_socket_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_socket(
        pargs_in->a_AddressFamily,
        pargs_in->a_Type,
        pargs_in->a_Protocol);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_WSACleanup(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_WSACleanup_args_t* pargs_in = (ocall_WSACleanup_args_t*) input_buffer;
    ocall_WSACleanup_args_t* pargs_out = (ocall_WSACleanup_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_WSACleanup(
        );

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_WSAStartup(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    ocall_WSAStartup_args_t* pargs_in = (ocall_WSAStartup_args_t*) input_buffer;
    ocall_WSAStartup_args_t* pargs_out = (ocall_WSAStartup_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_WSAStartup(
        );

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_host_exit(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    host_exit_args_t* pargs_in = (host_exit_args_t*) input_buffer;
    host_exit_args_t* pargs_out = (host_exit_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    host_exit(
        pargs_in->arg);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_host_create_thread(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    host_create_thread_args_t* pargs_in = (host_create_thread_args_t*) input_buffer;
    host_create_thread_args_t* pargs_out = (host_create_thread_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    host_create_thread(
        pargs_in->enc_key,
        pargs_in->enc);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_host_join_thread(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    host_join_thread_args_t* pargs_in = (host_join_thread_args_t*) input_buffer;
    host_join_thread_args_t* pargs_out = (host_join_thread_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = host_join_thread(
        pargs_in->enc_key);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_host_detach_thread(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    host_detach_thread_args_t* pargs_in = (host_detach_thread_args_t*) input_buffer;
    host_detach_thread_args_t* pargs_out = (host_detach_thread_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = host_detach_thread(
        pargs_in->enc_key);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_oe_host_ocall_pthread_condattr_init(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    oe_host_ocall_pthread_condattr_init_args_t* pargs_in = (oe_host_ocall_pthread_condattr_init_args_t*) input_buffer;
    oe_host_ocall_pthread_condattr_init_args_t* pargs_out = (oe_host_ocall_pthread_condattr_init_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(a, sizeof(pthread_condattr_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(a, sizeof(pthread_condattr_t));

    /* Call user function */
    pargs_out->_retval = oe_host_ocall_pthread_condattr_init(
        pargs_in->a);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_oe_host_ocall_pthread_condattr_destroy(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    oe_host_ocall_pthread_condattr_destroy_args_t* pargs_in = (oe_host_ocall_pthread_condattr_destroy_args_t*) input_buffer;
    oe_host_ocall_pthread_condattr_destroy_args_t* pargs_out = (oe_host_ocall_pthread_condattr_destroy_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(a, sizeof(pthread_condattr_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(a, sizeof(pthread_condattr_t));

    /* Call user function */
    pargs_out->_retval = oe_host_ocall_pthread_condattr_destroy(
        pargs_in->a);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_oe_host_ocall_pthread_condattr_getpshared(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    oe_host_ocall_pthread_condattr_getpshared_args_t* pargs_in = (oe_host_ocall_pthread_condattr_getpshared_args_t*) input_buffer;
    oe_host_ocall_pthread_condattr_getpshared_args_t* pargs_out = (oe_host_ocall_pthread_condattr_getpshared_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(a, sizeof(pthread_condattr_t));
    OE_SET_IN_OUT_POINTER(b, sizeof(int));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(b, sizeof(int));

    /* Call user function */
    pargs_out->_retval = oe_host_ocall_pthread_condattr_getpshared(
        (const pthread_condattr_t*) pargs_in->a,
        pargs_in->b);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_oe_host_ocall_pthread_condattr_setpshared(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    oe_host_ocall_pthread_condattr_setpshared_args_t* pargs_in = (oe_host_ocall_pthread_condattr_setpshared_args_t*) input_buffer;
    oe_host_ocall_pthread_condattr_setpshared_args_t* pargs_out = (oe_host_ocall_pthread_condattr_setpshared_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(a, sizeof(pthread_condattr_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(a, sizeof(pthread_condattr_t));

    /* Call user function */
    pargs_out->_retval = oe_host_ocall_pthread_condattr_setpshared(
        pargs_in->a,
        pargs_in->b);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_oe_host_ocall_pthread_condattr_getclock(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    oe_host_ocall_pthread_condattr_getclock_args_t* pargs_in = (oe_host_ocall_pthread_condattr_getclock_args_t*) input_buffer;
    oe_host_ocall_pthread_condattr_getclock_args_t* pargs_out = (oe_host_ocall_pthread_condattr_getclock_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(a, sizeof(pthread_condattr_t));
    OE_SET_IN_OUT_POINTER(b, sizeof(clockid_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(b, sizeof(clockid_t));

    /* Call user function */
    pargs_out->_retval = oe_host_ocall_pthread_condattr_getclock(
        (const pthread_condattr_t*) pargs_in->a,
        pargs_in->b);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_oe_host_ocall_pthread_condattr_setclock(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    oe_host_ocall_pthread_condattr_setclock_args_t* pargs_in = (oe_host_ocall_pthread_condattr_setclock_args_t*) input_buffer;
    oe_host_ocall_pthread_condattr_setclock_args_t* pargs_out = (oe_host_ocall_pthread_condattr_setclock_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(a, sizeof(pthread_condattr_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(a, sizeof(pthread_condattr_t));

    /* Call user function */
    pargs_out->_retval = oe_host_ocall_pthread_condattr_setclock(
        pargs_in->a,
        pargs_in->b);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_oe_host_ocall_pthread_attr_init(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    oe_host_ocall_pthread_attr_init_args_t* pargs_in = (oe_host_ocall_pthread_attr_init_args_t*) input_buffer;
    oe_host_ocall_pthread_attr_init_args_t* pargs_out = (oe_host_ocall_pthread_attr_init_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(a, sizeof(pthread_attr_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(a, sizeof(pthread_attr_t));

    /* Call user function */
    pargs_out->_retval = oe_host_ocall_pthread_attr_init(
        pargs_in->a);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_oe_host_ocall_pthread_attr_destroy(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    oe_host_ocall_pthread_attr_destroy_args_t* pargs_in = (oe_host_ocall_pthread_attr_destroy_args_t*) input_buffer;
    oe_host_ocall_pthread_attr_destroy_args_t* pargs_out = (oe_host_ocall_pthread_attr_destroy_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(a, sizeof(pthread_attr_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(a, sizeof(pthread_attr_t));

    /* Call user function */
    pargs_out->_retval = oe_host_ocall_pthread_attr_destroy(
        pargs_in->a);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_oe_host_ocall_pthread_attr_setdetachstate(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    oe_host_ocall_pthread_attr_setdetachstate_args_t* pargs_in = (oe_host_ocall_pthread_attr_setdetachstate_args_t*) input_buffer;
    oe_host_ocall_pthread_attr_setdetachstate_args_t* pargs_out = (oe_host_ocall_pthread_attr_setdetachstate_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(a, sizeof(pthread_attr_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(a, sizeof(pthread_attr_t));

    /* Call user function */
    pargs_out->_retval = oe_host_ocall_pthread_attr_setdetachstate(
        pargs_in->a,
        pargs_in->b);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_oe_host_ocall_eventfd(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    oe_host_ocall_eventfd_args_t* pargs_in = (oe_host_ocall_eventfd_args_t*) input_buffer;
    oe_host_ocall_eventfd_args_t* pargs_out = (oe_host_ocall_eventfd_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = oe_host_ocall_eventfd(
        pargs_in->a,
        pargs_in->b);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_oe_host_ocall_eventfd_read(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    oe_host_ocall_eventfd_read_args_t* pargs_in = (oe_host_ocall_eventfd_read_args_t*) input_buffer;
    oe_host_ocall_eventfd_read_args_t* pargs_out = (oe_host_ocall_eventfd_read_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(b, sizeof(eventfd_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(b, sizeof(eventfd_t));

    /* Call user function */
    pargs_out->_retval = oe_host_ocall_eventfd_read(
        pargs_in->a,
        pargs_in->b);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_oe_host_ocall_eventfd_write(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters */
    oe_host_ocall_eventfd_write_args_t* pargs_in = (oe_host_ocall_eventfd_write_args_t*) input_buffer;
    oe_host_ocall_eventfd_write_args_t* pargs_out = (oe_host_ocall_eventfd_write_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = oe_host_ocall_eventfd_write(
        pargs_in->a,
        pargs_in->b);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}


/*ocall function table*/
static oe_ocall_func_t __helloworld_ocall_function_table[]= {
    (oe_ocall_func_t) ocall_ocall_accept,
    (oe_ocall_func_t) ocall_ocall_bind,
    (oe_ocall_func_t) ocall_ocall_closesocket,
    (oe_ocall_func_t) ocall_ocall_connect,
    (oe_ocall_func_t) ocall_ocall_getaddrinfo,
    (oe_ocall_func_t) ocall_ocall_gethostname,
    (oe_ocall_func_t) ocall_ocall_getnameinfo,
    (oe_ocall_func_t) ocall_ocall_getpeername,
    (oe_ocall_func_t) ocall_ocall_getsockname,
    (oe_ocall_func_t) ocall_ocall_getsockopt,
    (oe_ocall_func_t) ocall_ocall_ioctlsocket,
    (oe_ocall_func_t) ocall_ocall_listen,
    (oe_ocall_func_t) ocall_ocall_recv,
    (oe_ocall_func_t) ocall_ocall_select,
    (oe_ocall_func_t) ocall_ocall_send,
    (oe_ocall_func_t) ocall_ocall_setsockopt,
    (oe_ocall_func_t) ocall_ocall_shutdown,
    (oe_ocall_func_t) ocall_ocall_socket,
    (oe_ocall_func_t) ocall_ocall_WSACleanup,
    (oe_ocall_func_t) ocall_ocall_WSAStartup,
    (oe_ocall_func_t) ocall_host_exit,
    (oe_ocall_func_t) ocall_host_create_thread,
    (oe_ocall_func_t) ocall_host_join_thread,
    (oe_ocall_func_t) ocall_host_detach_thread,
    (oe_ocall_func_t) ocall_oe_host_ocall_pthread_condattr_init,
    (oe_ocall_func_t) ocall_oe_host_ocall_pthread_condattr_destroy,
    (oe_ocall_func_t) ocall_oe_host_ocall_pthread_condattr_getpshared,
    (oe_ocall_func_t) ocall_oe_host_ocall_pthread_condattr_setpshared,
    (oe_ocall_func_t) ocall_oe_host_ocall_pthread_condattr_getclock,
    (oe_ocall_func_t) ocall_oe_host_ocall_pthread_condattr_setclock,
    (oe_ocall_func_t) ocall_oe_host_ocall_pthread_attr_init,
    (oe_ocall_func_t) ocall_oe_host_ocall_pthread_attr_destroy,
    (oe_ocall_func_t) ocall_oe_host_ocall_pthread_attr_setdetachstate,
    (oe_ocall_func_t) ocall_oe_host_ocall_eventfd,
    (oe_ocall_func_t) ocall_oe_host_ocall_eventfd_read,
    (oe_ocall_func_t) ocall_oe_host_ocall_eventfd_write,
    NULL
};

oe_result_t oe_create_helloworld_enclave(const char* path,
                                 oe_enclave_type_t type,
                                 uint32_t flags,
                                 const void* config,
                                 uint32_t config_size,
                                 oe_enclave_t** enclave)
{
    return oe_create_enclave(path,
               type,
               flags,
               config,
               config_size,
               __helloworld_ocall_function_table,
               36,
               enclave);
}

OE_EXTERNC_END
