/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_HELLOWORLD_T_H
#define EDGER8R_HELLOWORLD_T_H

#include <openenclave/enclave.h>
#include "helloworld_args.h"

OE_EXTERNC_BEGIN

/* List of ecalls */

int ecall_run(const char* input,
        uint64_t input_len,
        char** output,
        uint64_t max_len,
        uint64_t* output_len);
void ecall_InitializeSockets(void);
void enc_enclave_thread(uint64_t enc_key);

/* List of ocalls */

oe_result_t ocall_accept(
        accept_Result* _retval,
        intptr_t a_hSocket,
        int a_nAddrLen);
oe_result_t ocall_bind(
        oe_socket_error_t* _retval,
        intptr_t a_hSocket,
        const void* a_Name,
        int a_nNameLen);
oe_result_t ocall_closesocket(
        oe_socket_error_t* _retval,
        intptr_t a_hSocket);
oe_result_t ocall_connect(
        oe_socket_error_t* _retval,
        intptr_t a_hSocket,
        const void* a_Name,
        int a_nNameLen);
oe_result_t ocall_getaddrinfo(
        int* _retval,
        const char* a_NodeName,
        const char* a_ServiceName,
        int a_Flags,
        int a_Family,
        int a_SockType,
        int a_Protocol,
        addrinfo_Buffer* buf,
        size_t len,
        size_t* length_needed);
oe_result_t ocall_gethostname(
        gethostname_Result* _retval);
oe_result_t ocall_getnameinfo(
        getnameinfo_Result* _retval,
        const void* a_Addr,
        int a_AddrLen,
        int a_Flags);
oe_result_t ocall_getpeername(
        GetSockName_Result* _retval,
        intptr_t a_hSocket,
        int a_nNameLen);
oe_result_t ocall_getsockname(
        GetSockName_Result* _retval,
        intptr_t a_hSocket,
        int a_nNameLen);
oe_result_t ocall_getsockopt(
        getsockopt_Result* _retval,
        intptr_t a_hSocket,
        int a_nLevel,
        int a_nOptName,
        int a_nOptLen);
oe_result_t ocall_ioctlsocket(
        ioctlsocket_Result* _retval,
        intptr_t a_hSocket,
        int a_nCommand,
        unsigned int a_uInputValue);
oe_result_t ocall_listen(
        oe_socket_error_t* _retval,
        intptr_t a_hSocket,
        int a_nMaxConnections);
oe_result_t ocall_recv(
        ssize_t* _retval,
        intptr_t s,
        void* buf,
        size_t len,
        int flags,
        oe_socket_error_t* error);
oe_result_t ocall_select(
        select_Result* _retval,
        int a_nFds,
        oe_fd_set_internal a_ReadFds,
        oe_fd_set_internal a_WriteFds,
        oe_fd_set_internal a_ExceptFds,
        struct timeval a_Timeval);
oe_result_t ocall_send(
        send_Result* _retval,
        intptr_t a_hSocket,
        const void* a_Message,
        size_t a_nMessageLen,
        int a_Flags);
oe_result_t ocall_setsockopt(
        oe_socket_error_t* _retval,
        intptr_t a_hSocket,
        int a_nLevel,
        int a_nOptName,
        const void* a_OptVal,
        int a_nOptLen);
oe_result_t ocall_shutdown(
        oe_socket_error_t* _retval,
        intptr_t a_hSocket,
        oe_shutdown_how_t a_How);
oe_result_t ocall_socket(
        socket_Result* _retval,
        oe_socket_address_family_t a_AddressFamily,
        oe_socket_type_t a_Type,
        int a_Protocol);
oe_result_t ocall_WSACleanup(
        oe_socket_error_t* _retval);
oe_result_t ocall_WSAStartup(
        oe_socket_error_t* _retval);
oe_result_t host_exit(
        int arg);
oe_result_t host_create_thread(
        uint64_t enc_key,
        oe_enclave_t* enc);
oe_result_t host_join_thread(
        int* _retval,
        uint64_t enc_key);
oe_result_t host_detach_thread(
        int* _retval,
        uint64_t enc_key);
oe_result_t oe_host_ocall_pthread_condattr_init(
        oe_pthread_condattr_init_result_t* _retval,
        pthread_condattr_t* a);
oe_result_t oe_host_ocall_pthread_condattr_destroy(
        oe_pthread_condattr_destroy_result_t* _retval,
        pthread_condattr_t* a);
oe_result_t oe_host_ocall_pthread_condattr_getpshared(
        oe_pthread_condattr_getpshared_result_t* _retval,
        const pthread_condattr_t* a,
        int* b);
oe_result_t oe_host_ocall_pthread_condattr_setpshared(
        oe_pthread_condattr_setpshared_result_t* _retval,
        pthread_condattr_t* a,
        int b);
oe_result_t oe_host_ocall_pthread_condattr_getclock(
        oe_pthread_condattr_getclock_result_t* _retval,
        const pthread_condattr_t* a,
        clockid_t* b);
oe_result_t oe_host_ocall_pthread_condattr_setclock(
        oe_pthread_condattr_setclock_result_t* _retval,
        pthread_condattr_t* a,
        clockid_t b);
oe_result_t oe_host_ocall_pthread_attr_init(
        oe_pthread_attr_init_result_t* _retval,
        pthread_attr_t* a);
oe_result_t oe_host_ocall_pthread_attr_destroy(
        oe_pthread_attr_destroy_result_t* _retval,
        pthread_attr_t* a);
oe_result_t oe_host_ocall_pthread_attr_setdetachstate(
        oe_pthread_attr_setdetachstate_result_t* _retval,
        pthread_attr_t* a,
        int b);
oe_result_t oe_host_ocall_eventfd(
        oe_eventfd_result_t* _retval,
        unsigned int a,
        int b);
oe_result_t oe_host_ocall_eventfd_read(
        oe_eventfd_read_result_t* _retval,
        int a,
        eventfd_t* b);
oe_result_t oe_host_ocall_eventfd_write(
        oe_eventfd_write_result_t* _retval,
        int a,
        eventfd_t b);

OE_EXTERNC_END

#endif // EDGER8R_HELLOWORLD_T_H
